### PR TITLE
Count FPS in Renderer

### PR DESCRIPTION
**Pull request by navy1978**
Add getFps function to get FPS info also when not available from VLC

### CODE REVIEW

**Comment by luigiplr** [comment]
Would you mind also updating the read me accordingly? other than that looks great :+1:

**Comment by jaruba** [comment]
I'll update the readme for it, said I would :)

**Comment by jaruba** [comment]
Usage is just:

```
renderer.getFps(function(fps) {
    console.log('renderer fps is: ' + fps);
});
```

Takes exactly 1 second to respond, as it counts only after the request was made.

**Comment by jaruba** [comment]
Scenarios where this can be used:
- finding current FPS of live streams (I say `current`, because live streams can send a 30 fps video, then a 60 fps one, then a 10 fps one, and VLC returns `0` fps for live streams)
- checking rendering performance, like.. a 25 fps video rendering at only 22-23 fps means it's skipping frames so app performance is not optimal

**Comment by jaruba** [comment]
And it can be looped too to check FPS continually:

```
var checkFPS = function() {
    player.renderer.getFps(function(fps) {
        console.log('fps is: ' + fps);
        checkFPS();
    });
}
checkFPS();
```

_useful for finding out where the app is least performant in order to optimize it properly_

of course an alternative to this can be chromium's internal fps meter, but that's a different type of data

**Comment by jaruba** [comment]
One thing to note here is that even when VLC is paused, it still renders the same frame at 10 fps

**Comment by jaruba** [comment]
This change is now live. I published the new version on NPM.

**Comment by fleex** [comment]
Great! Thank you so much!

**Pull request merged**
